from flask import Flask, request, jsonify, Response
from flask_cors import CORS
from flask_compress import Compress
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import os
import re
from pathlib import Path
from dotenv import load_dotenv
from supabase import create_client

_ROOT = Path(__file__).resolve().parent.parent

app = Flask(__name__)
Compress(app)
CORS(app, origins=[
    "https://tinyhomeproject.netlify.app",
    "http://localhost:5173",
])

# Per-IP rate limiting on vote writes (in-memory storage is correct here: gunicorn is
# pinned to a single worker in gunicorn.conf.py, so there's exactly one limiter state).
# No default limit — GETs (map/tallies) stay unthrottled; write endpoints opt in below.
limiter = Limiter(get_remote_address, app=app, default_limits=[], storage_uri="memory://")

# Load environment variables
load_dotenv()

# Supabase setup. Prefer the service-role key (server-side only, bypasses RLS) so the
# database tables can have RLS enabled — with RLS on, the browser's anon key can no longer
# read/write votes directly via PostgREST; ALL vote traffic must flow through this backend,
# which verifies the caller's JWT (see require_user) before touching the DB.
supabase_url = os.getenv("SUPABASE_URL")
_service_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
_anon_key = os.getenv("SUPABASE_KEY")
supabase_key = _service_key or _anon_key
if _anon_key and not _service_key:
    print("WARNING: SUPABASE_SERVICE_ROLE_KEY not set — falling back to the anon key. "
          "Vote writes will FAIL once RLS is enabled on the votes tables. "
          "Set SUPABASE_SERVICE_ROLE_KEY in the environment (Render dashboard in production).")
supabase = create_client(supabase_url, supabase_key) if supabase_url and supabase_key else None


def require_user():
    """Verify the caller's Supabase JWT (Authorization: Bearer <token>) and return the
    authenticated user's id, or None if missing/invalid.

    Security: user identity must come from a verified token, never from the request body —
    otherwise anyone can vote as (or delete the votes of) any user whose UUID they know."""
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        return None
    token = auth_header[len("Bearer "):].strip()
    if not token or not supabase:
        return None
    try:
        res = supabase.auth.get_user(token)
        return res.user.id if res and res.user else None
    except Exception:
        return None

def parse_support(val):
    """Strictly interpret a vote's support value. Returns True/False, or None if invalid.
    Guards against Python's bool() coercion (bool("false") is True), which would silently
    record opposition as support and corrupt the research dataset."""
    if isinstance(val, bool):
        return val
    if isinstance(val, (int, float)) and val in (0, 1):
        return bool(val)
    if isinstance(val, str):
        s = val.strip().lower()
        if s in ("true", "yes", "1"):
            return True
        if s in ("false", "no", "0"):
            return False
    return None


# ── Load polygon parking data (generated by generate_parking_polygons.py) ──
_POLYGON_FILE = _ROOT / "data" / "polygons" / "parking_polygons_latest.geojson"
_poly_total = 0
try:
    with open(_POLYGON_FILE, encoding="utf-8") as _f:
        POLY_RAW = _f.read().replace(':NaN', ':null').replace(': NaN', ': null')
    _m = re.search(r'"total_spots":(\d+)', POLY_RAW)
    _poly_total = int(_m.group(1)) if _m else 0
    print(f"Loaded parking polygons ({_poly_total:,} spots).")
except Exception as _e:
    print(f"Warning: parking_polygons_latest.geojson not found ({_e}). Run generate_parking_polygons.py first.")
    POLY_RAW = '{"type":"FeatureCollection","total_spots":0,"features":[]}'
    _poly_total = 0

# Content-hash ETag so browsers cache this 52 MB payload and revalidate cheaply (304) on
# each page load instead of re-downloading + re-gzipping it every time. The hash changes
# only when the polygon data changes (a new pipeline run + deploy), forcing a fresh fetch.
import hashlib
POLY_ETAG = 'W/"' + hashlib.md5(POLY_RAW.encode("utf-8")).hexdigest() + '"'

@app.route("/api/votes/summary", methods=["GET"])
def get_votes_summary():
    if not supabase:
        return jsonify({"total_yes": 0}), 200
    try:
        # count="exact" returns the true total without the default 1,000-row page cap
        result = supabase.table("votes").select("id", count="exact").eq("support", True).execute()
        return jsonify({"total_yes": result.count or 0}), 200
    except Exception as e:
        print(f"Error fetching vote summary: {e}")
        return jsonify({"total_yes": 0}), 200

@app.route("/api/votes", methods=["GET"])
def get_votes():
    if not supabase:
        return jsonify({}), 200
    try:
        # Read pre-aggregated per-site tallies from the site_vote_summary view instead of
        # re-tallying every raw vote row in Python on each request. The DB does the GROUP BY,
        # and we ship one row per *voted* site rather than one per vote — this scales with the
        # number of voted sites (bounded), not the ever-growing total vote count.
        # The view LEFT JOINs all sites, so filter to voted ones; still paginate for the cap.
        counts = {}
        page = 0
        PAGE = 1000
        while True:
            start = page * PAGE
            result = (
                supabase.table("site_vote_summary")
                .select("site_id, support_count, oppose_count, total_votes")
                .gt("total_votes", 0)
                .range(start, start + PAGE - 1)
                .execute()
            )
            rows = result.data or []
            for row in rows:
                counts[row["site_id"]] = {
                    "yes": row.get("support_count") or 0,
                    "no": row.get("oppose_count") or 0,
                    "total": row.get("total_votes") or 0,
                }
            if len(rows) < PAGE:
                break
            page += 1
        return jsonify(counts), 200
    except Exception as e:
        print(f"Error fetching votes: {e}")
        return jsonify({}), 200

@app.route("/api/votes/mine", methods=["GET"])
def get_my_votes():
    """Return this AUTHENTICATED user's votes so they rehydrate on any device (the DB is the
    source of truth; localStorage is only a client-side cache). Identity comes from the
    verified JWT — a query-param user_id would let anyone enumerate any user's voting record
    by UUID.

    Response shape: the flat {site_id: support_bool} map as before, plus a "__comments__"
    entry holding {site_id: text} for the sites that actually have a note (they're rare), so
    the panel can prefill the textarea and let the user edit a note instead of silently
    overwriting it. Comments are smuggled in under a reserved key rather than nesting the
    votes under one because frontend and backend deploy separately — reshaping the response
    would break vote hydration for every client still running the old bundle. Real site_ids
    are "<osm_way>_<L|R>_<n>", so "__comments__" can never collide with one."""
    if not supabase:
        return jsonify({"__comments__": {}}), 200
    user_id = require_user()
    if not user_id:
        return jsonify({"error": "You must be logged in"}), 401
    try:
        # Paginate: PostgREST caps at 1,000 rows/query and one user may have more
        # (batch voting can select thousands of spots at once).
        mine = {}
        comments = {}
        page = 0
        PAGE = 1000
        while True:
            start = page * PAGE
            result = (
                supabase.table("votes")
                .select("site_id, support, comment")
                .eq("user_id", user_id)
                .range(start, start + PAGE - 1)
                .execute()
            )
            rows = result.data or []
            for row in rows:
                mine[row["site_id"]] = row["support"]
                if row.get("comment"):
                    comments[row["site_id"]] = row["comment"]
            if len(rows) < PAGE:
                break
            page += 1
        return jsonify({**mine, "__comments__": comments}), 200
    except Exception as e:
        print(f"Error fetching user's votes: {e}")
        return jsonify({"__comments__": {}}), 200

@app.route("/api/votes", methods=["POST"])
@limiter.limit("30/minute")
def submit_vote():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    # Identity comes ONLY from the verified JWT. Any user_id in the request body is
    # ignored — trusting it would let anyone vote as any user whose UUID they know.
    user_id = require_user()
    if not user_id:
        return jsonify({"error": "You must be logged in to vote"}), 401
    data = request.get_json(silent=True) or {}
    site_id = str(data.get("site_id", "")).strip()
    support = parse_support(data.get("support"))
    if not site_id or support is None:
        return jsonify({"error": "site_id and a boolean support are required"}), 400
    try:
        # An upsert replaces the whole row, so the presence of the "comment" key decides
        # what happens to an existing note: sending it (even as "") sets or clears the note,
        # omitting it preserves whatever is stored. Without this, any client that flips a
        # vote without knowing the current note would silently destroy it — which is exactly
        # how a real user's comment was lost.
        if "comment" in data:
            comment = ((data.get("comment") or "")[:500]) or None
        else:
            res = (
                supabase.table("votes")
                .select("comment")
                .eq("user_id", user_id)
                .eq("site_id", site_id)
                .limit(1)
                .execute()
            )
            comment = (res.data[0]["comment"] if res.data else None)
        row = {"site_id": site_id, "support": support,
               "comment": comment, "user_id": user_id}
        supabase.table("votes").upsert(row, on_conflict="user_id,site_id").execute()
        return jsonify({"status": "ok"}), 201
    except Exception as e:
        print(f"Error saving vote: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/votes", methods=["DELETE"])
@limiter.limit("30/minute")
def delete_vote():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    # Verified JWT only — a body user_id would let anyone delete another user's votes.
    user_id = require_user()
    if not user_id:
        return jsonify({"error": "You must be logged in"}), 401
    data = request.get_json(silent=True) or {}
    site_id = str(data.get("site_id", "")).strip()
    if not site_id:
        return jsonify({"error": "site_id is required"}), 400
    try:
        supabase.table("votes").delete().eq("site_id", site_id).eq("user_id", user_id).execute()
        return jsonify({"status": "ok"}), 200
    except Exception as e:
        print(f"Error deleting vote: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/votes/batch", methods=["POST"])
@limiter.limit("10/minute")
def submit_votes_batch():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    user_id = require_user()  # verified JWT only (see submit_vote)
    if not user_id:
        return jsonify({"error": "You must be logged in to vote"}), 401
    data = request.get_json(silent=True) or {}
    site_ids = data.get("site_ids", [])
    support = parse_support(data.get("support"))
    comment = (data.get("comment") or "")[:500]
    if not site_ids or support is None:
        return jsonify({"error": "site_ids and a boolean support are required"}), 400
    if len(site_ids) > 500:
        return jsonify({"error": "Too many site_ids (max 500)"}), 400
    try:
        ids = [str(sid) for sid in site_ids]
        # An upsert replaces the whole row, so a batch vote with an empty comment box would
        # null out notes the user had written on individual spots inside the selection. When
        # no batch comment is given, carry the existing ones through. Capped at 500 ids, so
        # this is one extra select per batch.
        existing = {}
        if not comment:
            res = (
                supabase.table("votes")
                .select("site_id, comment")
                .eq("user_id", user_id)
                .in_("site_id", ids)
                .execute()
            )
            existing = {r["site_id"]: r["comment"] for r in (res.data or []) if r.get("comment")}
        rows = [{"site_id": sid, "support": support,
                 "comment": comment or existing.get(sid), "user_id": user_id} for sid in ids]
        supabase.table("votes").upsert(rows, on_conflict="user_id,site_id").execute()
        return jsonify({"status": "ok", "count": len(rows)}), 201
    except Exception as e:
        print(f"Error saving batch votes: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/votes/batch", methods=["DELETE"])
@limiter.limit("10/minute")
def delete_votes_batch():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    user_id = require_user()  # verified JWT only (see delete_vote)
    if not user_id:
        return jsonify({"error": "You must be logged in"}), 401
    data = request.get_json(silent=True) or {}
    site_ids = data.get("site_ids", [])
    if not site_ids:
        return jsonify({"error": "site_ids is required"}), 400
    if len(site_ids) > 500:
        return jsonify({"error": "Too many site_ids (max 500)"}), 400
    try:
        supabase.table("votes").delete().in_("site_id", [str(s) for s in site_ids]).eq("user_id", user_id).execute()
        return jsonify({"status": "ok", "count": len(site_ids)}), 200
    except Exception as e:
        print(f"Error deleting batch votes: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

@app.route("/api/polygon_map", methods=["GET"])
def polygon_map():
    # Cheap revalidation: if the client already has this exact payload, return 304 (no body),
    # skipping the 52 MB send + gzip entirely.
    if request.headers.get("If-None-Match") == POLY_ETAG:
        return Response(status=304, headers={"ETag": POLY_ETAG, "Cache-Control": "no-cache"})
    resp = Response(POLY_RAW, mimetype="application/json")
    resp.headers["ETag"] = POLY_ETAG
    resp.headers["Cache-Control"] = "no-cache"   # cache, but always revalidate via ETag
    return resp

@app.route("/api/polygon_count", methods=["GET"])
def polygon_count():
    return jsonify({"total_spots": _poly_total})

@app.route("/healthz")
def healthz():
    return "OK", 200

@app.route("/api/ping", methods=["GET"])
def ping():
    """Keepalive endpoint — touches Supabase so the project doesn't pause. Deliberately does
    NOT swallow a failed Supabase touch: this is the only signal the GitHub Actions keepalive
    workflow has, so if the touch fails we must return a non-200 and let it propagate, or the
    workflow shows a false-positive green check while Supabase silently pauses anyway."""
    if not supabase:
        return jsonify({"status": "error", "detail": "Supabase client not configured"}), 500
    try:
        # Supabase's pause criteria wants "a few user requests to the database" per touch,
        # not one — so this is 3 distinct real queries against 3 different tables, not 1.
        supabase.table("votes").select("id").limit(1).execute()
        supabase.table("sites").select("site_id").limit(1).execute()
        supabase.table("vote_events").select("id").limit(1).execute()
    except Exception as e:
        print(f"Keepalive ping failed to touch Supabase: {e}")
        return jsonify({"status": "error", "detail": str(e)}), 502
    return jsonify({"status": "ok"}), 200

@app.route("/api/suggestions", methods=["GET"])
def get_suggestions():
    if not supabase:
        return jsonify([]), 200
    try:
        # Deliberately exclude name/occupation: this endpoint is public and those fields
        # are submitter PII. The map only needs location + reason for its markers.
        result = supabase.table("suggestions").select("id, lat, lng, reason, created_at").execute()
        return jsonify(result.data), 200
    except Exception as e:
        print(f"Error fetching suggestions: {e}")
        return jsonify([]), 200

@app.route("/api/suggestions", methods=["POST"])
def submit_suggestion():
    if not supabase:
        return jsonify({"error": "Database not configured"}), 500
    data = request.get_json(silent=True) or {}
    try:
        supabase.table("suggestions").insert({
            "lat": float(data["lat"]),
            "lng": float(data["lng"]),
            "name": (data.get("name") or "")[:200] or None,
            "occupation": (data.get("occupation") or "")[:200] or None,
            "reason": (data.get("reason") or "")[:500] or None,
        }).execute()
        return jsonify({"status": "ok"}), 201
    except Exception as e:
        print(f"Error saving suggestion: {e}")
        return jsonify({"error": "Something went wrong. Please try again."}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)
